// Copyright 2026 The Natscope Authors
// SPDX-License-Identifier: Apache-2.0

package proto

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dmit-4884/natscope/internal/entities"
)

// Cache fixtures (mirrored from pkg/protoutils tests) to exercise the buf cache
// layout end-to-end through compile().

const (
	fixtureCommitProtovalidate = "80ab13bee0bf4272b6161a72bf7034e0"
	fixtureCommitGoogleapis    = "c17df5b2beca46928cc87d5656bd5343"
	fixtureCommitAlt           = "50325440f8f24053b047484a6bf60b76"

	fixtureDigestB5 = "b5:17d47fa0d4c9f9ea2f9ea4e94e9dfe91b6c8b2a0fd2e71a9c"
	fixtureDigestB4 = "shake256:e8f475fe3330f31f5fd86ac689093bcd274e19611a09db91"

	canonicalModuleYAML = "version: v1\nfiles_dir: files\n"
	customFilesDirYAML  = "version: v1\nfiles_dir: src\n"
)

const fixtureValidateProto = `syntax = "proto2";
package buf.validate;

import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  optional FieldConstraints field = 1159;
}
extend google.protobuf.MessageOptions {
  optional MessageConstraints message = 1159;
}

message FieldConstraints {
  optional bool required = 25;
  optional StringRules string = 14;
}

message MessageConstraints {
  optional bool disabled = 1;
}

message StringRules {
  optional uint64 min_len = 2;
  optional uint64 max_len = 3;
  optional string pattern = 4;
}
`

const fixtureGoogleApiAnnotationsProto = `syntax = "proto3";
package google.api;

import "google/api/http.proto";
import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
  HttpRule http = 72295728;
}
`

const fixtureGoogleApiHttpProto = `syntax = "proto3";
package google.api;

message HttpRule {
  string selector = 1;
  string get = 2;
  string put = 3;
  string post = 4;
}
`

type cacheBuilder struct {
	t    *testing.T
	root string
}

func newCache(t *testing.T) *cacheBuilder {
	t.Helper()
	return &cacheBuilder{t: t, root: t.TempDir()}
}

func (c *cacheBuilder) addModule(digestType, name, commit, moduleYAML string, files map[string]string) string {
	c.t.Helper()
	modDir := filepath.Join(c.root, "v3", "modules", digestType, filepath.FromSlash(name), commit)
	require.NoError(c.t, os.MkdirAll(modDir, 0o755))

	if moduleYAML != "" {
		require.NoError(c.t, os.WriteFile(filepath.Join(modDir, "module.yaml"), []byte(moduleYAML), 0o644))
	}

	for rel, content := range files {
		full := filepath.Join(modDir, rel)
		require.NoError(c.t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(c.t, os.WriteFile(full, []byte(content), 0o644))
	}
	return modDir
}

func (c *cacheBuilder) addProtovalidate(digestType, commit string) string {
	return c.addModule(digestType, "buf.build/bufbuild/protovalidate", commit, canonicalModuleYAML, map[string]string{
		"files/buf/validate/validate.proto": fixtureValidateProto,
		"files/LICENSE":                     "Apache 2.0",
		"files/README.md":                   "# protovalidate",
	})
}

func (c *cacheBuilder) addGoogleapisMinimal(digestType, commit string) string {
	return c.addModule(digestType, "buf.build/googleapis/googleapis", commit, canonicalModuleYAML, map[string]string{
		"files/google/api/annotations.proto": fixtureGoogleApiAnnotationsProto,
		"files/google/api/http.proto":        fixtureGoogleApiHttpProto,
	})
}

func writeBufLock(t *testing.T, sourceRoot, body string) string {
	t.Helper()
	require.NoError(t, os.MkdirAll(sourceRoot, 0o755))
	p := filepath.Join(sourceRoot, "buf.lock")
	require.NoError(t, os.WriteFile(p, []byte(body), 0o644))
	return p
}

func bufLockV2Single(commit, digest string) string {
	return `# Generated by buf. DO NOT EDIT.
version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + commit + `
    digest: ` + digest + `
`
}

func bufLockV2MultipleDeps() string {
	return `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
  - name: buf.build/googleapis/googleapis
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
`
}

// TestCompileWithBufDeps wires the compiler against a fake cache; failure means
// "Compile Now" breaks for real buf.lock'd projects.
func TestCompileWithBufDeps(t *testing.T) {
	// Not t.Parallel: subtests t.Setenv BUF_CACHE_DIR.

	setIsolatedCache := func(t *testing.T, cacheRoot string) {
		t.Helper()
		t.Setenv("BUF_CACHE_DIR", cacheRoot)
	}

	const userProtoImportingProtovalidate = `syntax = "proto2";
package blitz.types;

import "buf/validate/validate.proto";

message User {
  optional string name = 1 [(buf.validate.field).string.min_len = 1];
}
`

	// No overrides, so the ladder falls through to suffix inference + buf.lock
	// dep resolution from diskRoot.
	localSrc := &entities.ProtoSource{Name: "buf-deps", SourceType: entities.SourceTypeLocal, Enabled: true}

	t.Run("compiles_proto_that_imports_protovalidate", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))

		svc := newTestService(nil, nil, nil, nil, nil)

		files := []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}

		out, err := svc.compile(t.Context(), localSrc, files, nil, src)
		require.NoError(t, err, "proto that imports buf/validate/validate.proto must compile when buf cache is populated")
		require.False(t, out.HasErrors())
		require.NotEmpty(t, out.FDS)
	})

	t.Run("fails_without_buf_lock", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		setIsolatedCache(t, c.root)

		src := t.TempDir() // no buf.lock
		svc := newTestService(nil, nil, nil, nil, nil)

		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err)
		require.True(t, out.HasErrors(), "without buf.lock we have no way to locate BSR deps")
		assert.Contains(t, summarizeDiagnostics(out.Diags), "validate.proto")
	})

	t.Run("fails_on_stale_commit_not_in_cache", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(strings.Repeat("0", 32), fixtureDigestB5))

		svc := newTestService(nil, nil, nil, nil, nil)
		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err)
		require.True(t, out.HasErrors(), "lock commit not in cache must cause compile failure")
	})

	t.Run("fails_when_cache_entry_has_no_module_yaml", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/bufbuild/protovalidate", fixtureCommitProtovalidate, "", map[string]string{
			"files/buf/validate/validate.proto": fixtureValidateProto,
		})
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))

		svc := newTestService(nil, nil, nil, nil, nil)
		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err)
		require.True(t, out.HasErrors(), "module.yaml is the cache validity marker — without it, treat as missing")
	})

	t.Run("custom_files_dir_resolves", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/bufbuild/protovalidate", fixtureCommitProtovalidate, customFilesDirYAML, map[string]string{
			"src/buf/validate/validate.proto": fixtureValidateProto,
		})
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		svc := newTestService(nil, nil, nil, nil, nil)

		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err, "compiler must honor files_dir specified in module.yaml")
		require.False(t, out.HasErrors())
		require.NotEmpty(t, out.FDS)
	})

	t.Run("two_BSR_deps_both_needed", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		c.addGoogleapisMinimal("b5", fixtureCommitGoogleapis)
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2MultipleDeps())

		userProto := `syntax = "proto3";
package blitz.api;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";

message Ping { string id = 1; }
`
		svc := newTestService(nil, nil, nil, nil, nil)
		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/api/ping.proto", Content: userProto},
		}, nil, src)
		require.NoError(t, err)
		require.False(t, out.HasErrors())
		require.NotEmpty(t, out.FDS)
	})

	t.Run("b4_digest_cache_entry_resolves", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b4", fixtureCommitProtovalidate)
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB4))

		svc := newTestService(nil, nil, nil, nil, nil)
		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err, "shake256 (b4) digest in lock must map to b4 cache dir")
		require.False(t, out.HasErrors())
	})

	t.Run("self_hosted_BSR_registry_compiles", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "bsr.acme.internal/shared/types", fixtureCommitAlt, canonicalModuleYAML, map[string]string{
			"files/acme/shared/core.proto": `syntax = "proto3";
package acme.shared;
message Id { string value = 1; }
`,
		})
		setIsolatedCache(t, c.root)

		src := t.TempDir()
		writeBufLock(t, src, `version: v2
deps:
  - name: bsr.acme.internal/shared/types
    commit: `+fixtureCommitAlt+`
    digest: `+fixtureDigestB5+`
`)

		userProto := `syntax = "proto3";
package blitz.api;

import "acme/shared/core.proto";

message WithId {
  acme.shared.Id id = 1;
}
`
		svc := newTestService(nil, nil, nil, nil, nil)
		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/api/with_id.proto", Content: userProto},
		}, nil, src)
		require.NoError(t, err)
		require.False(t, out.HasErrors())
		require.NotEmpty(t, out.FDS)
	})

	t.Run("XDG_CACHE_HOME_override_honored", func(t *testing.T) {
		if runtime.GOOS == "windows" {
			t.Skip("XDG is unix-only")
		}
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		t.Setenv("BUF_CACHE_DIR", "")
		xdgCache := filepath.Join(t.TempDir(), "xdg-root")
		require.NoError(t, os.MkdirAll(filepath.Join(xdgCache, "buf"), 0o755))
		relocateCache(t, c.root, filepath.Join(xdgCache, "buf"))
		t.Setenv("XDG_CACHE_HOME", xdgCache)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		svc := newTestService(nil, nil, nil, nil, nil)

		out, err := svc.compile(t.Context(), localSrc, []entities.ProtoFileEntry{
			{Path: "blitz/types/user.proto", Content: userProtoImportingProtovalidate},
		}, nil, src)
		require.NoError(t, err, "XDG_CACHE_HOME/buf must be discovered without BUF_CACHE_DIR")
		require.False(t, out.HasErrors())
	})
}

// relocateCache moves the v3/ subtree from src to dst (dst must exist) to test
// env-var-driven cache discovery.
func relocateCache(t *testing.T, src, dst string) {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(src, "v3"))
	require.NoError(t, err)
	require.NoError(t, os.MkdirAll(filepath.Join(dst, "v3"), 0o755))
	for _, e := range entries {
		require.NoError(t, os.Rename(
			filepath.Join(src, "v3", e.Name()),
			filepath.Join(dst, "v3", e.Name()),
		))
	}
}
