// Copyright 2026 The Natscope Authors
// SPDX-License-Identifier: Apache-2.0

package protoutils

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	fixtureCommitProtovalidate = "80ab13bee0bf4272b6161a72bf7034e0"
	fixtureCommitGoogleapis    = "c17df5b2beca46928cc87d5656bd5343"
	fixtureCommitAlt           = "50325440f8f24053b047484a6bf60b76"

	fixtureDigestB5     = "b5:17d47fa0d4c9f9ea2f9ea4e94e9dfe91b6c8b2a0fd2e71a9c"
	fixtureDigestB4     = "shake256:e8f475fe3330f31f5fd86ac689093bcd274e19611a09db91"
	fixtureDigestBadPfx = "sha256:feedface"

	canonicalModuleYAML = "version: v1\nfiles_dir: files\n"
	customFilesDirYAML  = "version: v1\nfiles_dir: src\n"
	wrongVersionYAML    = "version: v2\nfiles_dir: files\n"
	emptyFilesDirYAML   = "version: v1\nfiles_dir:\n"
)

const fixtureValidateProto = `syntax = "proto2";
package buf.validate;

import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  optional FieldConstraints field = 1159;
}
extend google.protobuf.MessageOptions {
  optional MessageConstraints message = 1159;
}

message FieldConstraints {
  optional bool required = 25;
  optional StringRules string = 14;
}

message MessageConstraints {
  optional bool disabled = 1;
}

message StringRules {
  optional uint64 min_len = 2;
  optional uint64 max_len = 3;
  optional string pattern = 4;
}
`

const fixtureGoogleApiAnnotationsProto = `syntax = "proto3";
package google.api;

import "google/api/http.proto";
import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
  HttpRule http = 72295728;
}
`

const fixtureGoogleApiHttpProto = `syntax = "proto3";
package google.api;

message HttpRule {
  string selector = 1;
  string get = 2;
  string put = 3;
  string post = 4;
}
`

type cacheBuilder struct {
	t    *testing.T
	root string
}

func newCache(t *testing.T) *cacheBuilder {
	t.Helper()
	return &cacheBuilder{t: t, root: t.TempDir()}
}

func (c *cacheBuilder) addModule(digestType, name, commit, moduleYAML string, files map[string]string) string {
	c.t.Helper()
	modDir := filepath.Join(c.root, "v3", "modules", digestType, filepath.FromSlash(name), commit)
	require.NoError(c.t, os.MkdirAll(modDir, 0o755))

	if moduleYAML != "" {
		require.NoError(c.t, os.WriteFile(filepath.Join(modDir, "module.yaml"), []byte(moduleYAML), 0o644))
	}

	for rel, content := range files {
		full := filepath.Join(modDir, rel)
		require.NoError(c.t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(c.t, os.WriteFile(full, []byte(content), 0o644))
	}
	return modDir
}

func (c *cacheBuilder) addProtovalidate(digestType, commit string) string {
	return c.addModule(digestType, "buf.build/bufbuild/protovalidate", commit, canonicalModuleYAML, map[string]string{
		"files/buf/validate/validate.proto": fixtureValidateProto,
		"files/LICENSE":                     "Apache 2.0",
		"files/README.md":                   "# protovalidate",
	})
}

func (c *cacheBuilder) addGoogleapisMinimal(digestType, commit string) string {
	return c.addModule(digestType, "buf.build/googleapis/googleapis", commit, canonicalModuleYAML, map[string]string{
		"files/google/api/annotations.proto": fixtureGoogleApiAnnotationsProto,
		"files/google/api/http.proto":        fixtureGoogleApiHttpProto,
	})
}

func writeBufLock(t *testing.T, sourceRoot, body string) string {
	t.Helper()
	require.NoError(t, os.MkdirAll(sourceRoot, 0o755))
	p := filepath.Join(sourceRoot, "buf.lock")
	require.NoError(t, os.WriteFile(p, []byte(body), 0o644))
	return p
}

func bufLockV2Single(commit, digest string) string {
	return `# Generated by buf. DO NOT EDIT.
version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + commit + `
    digest: ` + digest + `
`
}

func bufLockV2MultipleDeps() string {
	return `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
  - name: buf.build/googleapis/googleapis
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
`
}

func TestDefaultBufCacheDir(t *testing.T) {
	t.Run("BUF_CACHE_DIR_wins_over_everything", func(t *testing.T) {
		t.Setenv("BUF_CACHE_DIR", "/custom/buf-cache")
		t.Setenv("XDG_CACHE_HOME", "/ignored/xdg")
		t.Setenv("HOME", "/ignored/home")
		assert.Equal(t, "/custom/buf-cache", defaultBufCacheDir())
	})

	t.Run("BUF_CACHE_DIR_used_verbatim_without_buf_suffix", func(t *testing.T) {
		t.Setenv("BUF_CACHE_DIR", "/already/has/buf")
		got := defaultBufCacheDir()
		assert.Equal(t, "/already/has/buf", got, "buf CLI does NOT append /buf when BUF_CACHE_DIR is set")
	})

	t.Run("BUF_CACHE_DIR_leading_and_trailing_whitespace_stripped", func(t *testing.T) {
		t.Setenv("BUF_CACHE_DIR", "   /trimmed/path   ")
		assert.Equal(t, "/trimmed/path", defaultBufCacheDir())
	})

	t.Run("BUF_CACHE_DIR_empty_falls_through", func(t *testing.T) {
		t.Setenv("BUF_CACHE_DIR", "")
		t.Setenv("XDG_CACHE_HOME", "/x")
		if runtime.GOOS == "windows" {
			t.Setenv("LocalAppData", `C:\AppData`)
			assert.Equal(t, filepath.Join(`C:\AppData`, "buf"), defaultBufCacheDir())
			return
		}
		assert.Equal(t, "/x/buf", defaultBufCacheDir())
	})

	t.Run("BUF_CACHE_DIR_whitespace_only_falls_through", func(t *testing.T) {
		if runtime.GOOS == "windows" {
			t.Skip("unix-only fallthrough test")
		}
		t.Setenv("BUF_CACHE_DIR", "   \t  ")
		t.Setenv("XDG_CACHE_HOME", "/xdg")
		assert.Equal(t, "/xdg/buf", defaultBufCacheDir())
	})

	t.Run("unix_XDG_CACHE_HOME_appends_buf", func(t *testing.T) {
		if runtime.GOOS == "windows" {
			t.Skip("unix-only test")
		}
		t.Setenv("BUF_CACHE_DIR", "")
		t.Setenv("XDG_CACHE_HOME", "/xdg/home")
		assert.Equal(t, "/xdg/home/buf", defaultBufCacheDir())
	})

	t.Run("unix_falls_back_to_home_dot_cache", func(t *testing.T) {
		if runtime.GOOS == "windows" {
			t.Skip("unix-only test")
		}
		t.Setenv("BUF_CACHE_DIR", "")
		t.Setenv("XDG_CACHE_HOME", "")
		t.Setenv("HOME", "/home/tester")
		assert.Equal(t, "/home/tester/.cache/buf", defaultBufCacheDir())
	})

	t.Run("macos_does_NOT_use_library_caches", func(t *testing.T) {
		if runtime.GOOS != "darwin" {
			t.Skip("darwin-only test — buf uses XDG on macOS, not ~/Library/Caches")
		}
		t.Setenv("BUF_CACHE_DIR", "")
		t.Setenv("XDG_CACHE_HOME", "")
		t.Setenv("HOME", "/Users/tester")
		got := defaultBufCacheDir()
		assert.Equal(t, "/Users/tester/.cache/buf", got)
		assert.NotContains(t, got, "Library/Caches",
			"buf deliberately avoids ~/Library/Caches on macOS — see app_unix.go comment")
	})

	t.Run("windows_uses_LocalAppData", func(t *testing.T) {
		if runtime.GOOS != "windows" {
			t.Skip("windows-only test")
		}
		t.Setenv("BUF_CACHE_DIR", "")
		t.Setenv("LocalAppData", `C:\Users\x\AppData\Local`)
		assert.Equal(t, `C:\Users\x\AppData\Local\buf`, defaultBufCacheDir())
	})
}

func TestParseBufLock(t *testing.T) {
	t.Parallel()

	t.Run("v2_single_dep_b5", func(t *testing.T) {
		body := `# Generated by buf. DO NOT EDIT.
version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
		assert.Equal(t, fixtureCommitProtovalidate, deps[0].Commit)
		assert.Equal(t, "b5", deps[0].DigestType)
	})

	t.Run("v2_multiple_deps", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
  - name: buf.build/googleapis/googleapis
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 2)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
		assert.Equal(t, "buf.build/googleapis/googleapis", deps[1].Name)
	})

	t.Run("v2_with_plugins_and_policies_sections_ignored", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
plugins:
  - name: buf.build/some/plugin
    commit: ffffffffffffffffffffffffffffffff
    digest: ` + fixtureDigestB5 + `
policies:
  - name: buf.build/some/policy
    commit: eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		assert.GreaterOrEqual(t, len(deps), 1)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
	})

	t.Run("v2_skips_entry_with_missing_digest", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
  - name: buf.build/googleapis/googleapis
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/googleapis/googleapis", deps[0].Name)
	})

	t.Run("v2_skips_entry_with_missing_commit", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_skips_entry_with_missing_name", func(t *testing.T) {
		body := `version: v2
deps:
  - commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_rejects_dashed_commit", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: 80ab13be-e0bf-4272-b616-1a72bf7034e0
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)),
			"buf.lock uses dashless 32-hex; dashed form must be rejected")
	})

	t.Run("v2_rejects_unknown_digest_prefix", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestBadPfx + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_rejects_short_commit", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: abcd1234
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_rejects_long_commit", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `00
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_normalizes_uppercase_commit_to_lowercase", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: 80AB13BEE0BF4272B6161A72BF7034E0
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, fixtureCommitProtovalidate, deps[0].Commit, "uppercase hex normalized")
	})

	t.Run("v2_rejects_hex_with_non_hex_char", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: zzab13bee0bf4272b6161a72bf7034e0
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v2_shake256_digest_maps_to_b4", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB4 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "b4", deps[0].DigestType)
	})

	t.Run("v1_modern_minimal_form", func(t *testing.T) {
		body := `# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: bufbuild
    repository: protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
		assert.Equal(t, "b5", deps[0].DigestType)
	})

	t.Run("v1_legacy_form_with_branch_and_create_time_ignored", func(t *testing.T) {
		body := `version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
    create_time: 2023-01-01T00:00:00Z
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/googleapis/googleapis", deps[0].Name)
	})

	t.Run("v1_skips_entry_missing_owner", func(t *testing.T) {
		body := `version: v1
deps:
  - remote: buf.build
    repository: protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("v1_skips_entry_missing_repository", func(t *testing.T) {
		body := `version: v1
deps:
  - remote: buf.build
    owner: bufbuild
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("mixed_v1_and_v2_entries_best_effort", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: ` + fixtureCommitGoogleapis + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 2)
		names := []string{deps[0].Name, deps[1].Name}
		sort.Strings(names)
		assert.Equal(t, []string{
			"buf.build/bufbuild/protovalidate",
			"buf.build/googleapis/googleapis",
		}, names)
	})

	t.Run("empty_lock_only_version_no_deps", func(t *testing.T) {
		assert.Empty(t, parseBufLock([]byte("version: v2\n")))
	})

	t.Run("empty_lock_empty_bytes", func(t *testing.T) {
		assert.Empty(t, parseBufLock(nil))
		assert.Empty(t, parseBufLock([]byte{}))
	})

	t.Run("ignores_blank_lines_and_comments", func(t *testing.T) {
		body := `
# top comment

version: v2
# before deps

deps:

  - name: buf.build/bufbuild/protovalidate
    # mid-entry comment
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `

`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
	})

	t.Run("self_hosted_BSR_registry_accepted", func(t *testing.T) {
		body := `version: v2
deps:
  - name: bsr.acme.internal/payments/api
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "bsr.acme.internal/payments/api", deps[0].Name)
	})

	t.Run("self_hosted_BSR_with_port", func(t *testing.T) {
		body := `version: v2
deps:
  - name: bsr.acme.internal:8443/payments/api
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "bsr.acme.internal:8443/payments/api", deps[0].Name)
	})

	t.Run("rejects_name_with_only_two_parts", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/onlytwo
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("rejects_name_with_four_parts", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/owner/name/extra
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("rejects_name_with_disallowed_chars", func(t *testing.T) {
		body := `version: v2
deps:
  - name: buf.build/owner with space/name
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		assert.Empty(t, parseBufLock([]byte(body)))
	})

	t.Run("handles_quoted_values", func(t *testing.T) {
		body := `version: v2
deps:
  - name: "buf.build/bufbuild/protovalidate"
    commit: '` + fixtureCommitProtovalidate + `'
    digest: "` + fixtureDigestB5 + `"
`
		deps := parseBufLock([]byte(body))
		require.Len(t, deps, 1)
		assert.Equal(t, "buf.build/bufbuild/protovalidate", deps[0].Name)
		assert.Equal(t, fixtureCommitProtovalidate, deps[0].Commit)
	})
}

func TestReadModuleFilesDir(t *testing.T) {
	t.Parallel()

	write := func(t *testing.T, body string) string {
		t.Helper()
		p := filepath.Join(t.TempDir(), "module.yaml")
		require.NoError(t, os.WriteFile(p, []byte(body), 0o644))
		return p
	}

	t.Run("canonical_v1_files_dir_files", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, canonicalModuleYAML))
		require.True(t, ok)
		assert.Equal(t, "files", got)
	})

	t.Run("custom_files_dir_value_honored", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, customFilesDirYAML))
		require.True(t, ok)
		assert.Equal(t, "src", got, "files_dir is NOT hard-coded — buf may publish with custom")
	})

	t.Run("missing_file_returns_false", func(t *testing.T) {
		got, ok := readModuleFilesDir(filepath.Join(t.TempDir(), "does-not-exist.yaml"))
		assert.False(t, ok)
		assert.Empty(t, got)
	})

	t.Run("version_v2_treated_as_invalid_cache", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, wrongVersionYAML))
		assert.False(t, ok)
		assert.Empty(t, got)
	})

	t.Run("empty_files_dir_rejected", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, emptyFilesDirYAML))
		assert.False(t, ok)
		assert.Empty(t, got)
	})

	t.Run("unknown_top_level_fields_ignored", func(t *testing.T) {
		body := `version: v1
files_dir: files
some_new_field: banana
another: thing
`
		got, ok := readModuleFilesDir(write(t, body))
		require.True(t, ok)
		assert.Equal(t, "files", got)
	})

	t.Run("comments_and_blank_lines_ignored", func(t *testing.T) {
		body := `# comment
version: v1

# another
files_dir: files # trailing
`
		got, ok := readModuleFilesDir(write(t, body))
		require.True(t, ok)
		assert.Equal(t, "files", got, "inline comments after ' #' stripped from value")
	})

	t.Run("deps_list_does_not_leak_into_top_level", func(t *testing.T) {
		body := `version: v1
files_dir: files
deps:
  - name: buf.build/x/y
    files_dir: NESTED
`
		got, ok := readModuleFilesDir(write(t, body))
		require.True(t, ok)
		assert.Equal(t, "files", got)
	})

	t.Run("completely_empty_file_rejected", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, ""))
		assert.False(t, ok)
		assert.Empty(t, got)
	})

	t.Run("only_garbage_rejected", func(t *testing.T) {
		got, ok := readModuleFilesDir(write(t, "🦑🦑🦑\nnot yaml at all"))
		assert.False(t, ok)
		assert.Empty(t, got)
	})
}

func TestResolveModuleFilesDir(t *testing.T) {
	t.Parallel()

	t.Run("happy_path_b5_canonical", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		got, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     fixtureCommitProtovalidate,
			DigestType: "b5",
		})
		require.True(t, ok)
		assert.True(t, strings.HasSuffix(got, filepath.Join("80ab13bee0bf4272b6161a72bf7034e0", "files")))
		info, err := os.Stat(filepath.Join(got, "buf", "validate", "validate.proto"))
		require.NoError(t, err)
		assert.False(t, info.IsDir())
	})

	t.Run("custom_files_dir", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/acme/custom", fixtureCommitAlt, customFilesDirYAML, map[string]string{
			"src/acme/api.proto": "syntax = \"proto3\"; package acme;",
		})

		got, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/acme/custom",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		require.True(t, ok)
		assert.True(t, strings.HasSuffix(got, "src"))
	})

	t.Run("b4_digest_type_lookup", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b4", fixtureCommitProtovalidate)

		got, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     fixtureCommitProtovalidate,
			DigestType: "b4",
		})
		require.True(t, ok)
		assert.Contains(t, got, filepath.Join("v3", "modules", "b4"))
	})

	t.Run("digest_mismatch_between_lock_and_cache_is_a_miss", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b4", fixtureCommitProtovalidate)

		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     fixtureCommitProtovalidate,
			DigestType: "b5",
		})
		assert.False(t, ok)
	})

	t.Run("module_dir_missing_cache_miss", func(t *testing.T) {
		c := newCache(t)
		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/nonexistent/module",
			Commit:     fixtureCommitProtovalidate,
			DigestType: "b5",
		})
		assert.False(t, ok)
	})

	t.Run("missing_module_yaml_treated_as_incomplete_cache", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/x/y", fixtureCommitAlt, "", map[string]string{
			"files/x/y.proto": "syntax = \"proto3\";",
		})
		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/x/y",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		assert.False(t, ok, "module.yaml is the validity marker — buf writes it last")
	})

	t.Run("files_subdir_missing_cache_miss", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/x/y", fixtureCommitAlt, canonicalModuleYAML, nil)
		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/x/y",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		assert.False(t, ok)
	})

	t.Run("wrong_commit_cache_miss", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     strings.Repeat("0", 32),
			DigestType: "b5",
		})
		assert.False(t, ok)
	})

	t.Run("self_hosted_BSR_registry_resolves", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "bsr.acme.internal/payments/api", fixtureCommitAlt, canonicalModuleYAML, map[string]string{
			"files/acme/payments/api.proto": "syntax = \"proto3\";",
		})

		got, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "bsr.acme.internal/payments/api",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		require.True(t, ok)
		assert.Contains(t, got, filepath.Join("bsr.acme.internal", "payments", "api"))
	})

	t.Run("two_commits_same_module_coexist", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		c.addProtovalidate("b5", fixtureCommitAlt)

		got1, ok1 := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     fixtureCommitProtovalidate,
			DigestType: "b5",
		})
		got2, ok2 := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/bufbuild/protovalidate",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		require.True(t, ok1)
		require.True(t, ok2)
		assert.NotEqual(t, got1, got2)
	})

	t.Run("invalid_module_yaml_version_cache_miss", func(t *testing.T) {
		c := newCache(t)
		c.addModule("b5", "buf.build/x/y", fixtureCommitAlt, wrongVersionYAML, map[string]string{
			"files/x.proto": "syntax = \"proto3\";",
		})
		_, ok := resolveModuleFilesDir(c.root, bufDep{
			Name:       "buf.build/x/y",
			Commit:     fixtureCommitAlt,
			DigestType: "b5",
		})
		assert.False(t, ok, "module.yaml version != v1 must be treated as incompatible")
	})
}

func TestResolveBufDepsWith(t *testing.T) {
	t.Parallel()

	t.Run("happy_path_single_dep", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))

		got := resolveBufDepsWith(src, c.root)
		require.Len(t, got, 1)
		assert.True(t, strings.HasSuffix(got[0], "files"))
	})

	t.Run("multiple_deps_all_resolve", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		c.addGoogleapisMinimal("b5", fixtureCommitGoogleapis)
		src := t.TempDir()
		writeBufLock(t, src, bufLockV2MultipleDeps())

		got := resolveBufDepsWith(src, c.root)
		require.Len(t, got, 2)
	})

	t.Run("some_deps_missing_from_cache_returns_only_resolved", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		src := t.TempDir()
		writeBufLock(t, src, bufLockV2MultipleDeps())

		got := resolveBufDepsWith(src, c.root)
		require.Len(t, got, 1)
		assert.Contains(t, got[0], "protovalidate")
	})

	t.Run("no_source_root_returns_nil", func(t *testing.T) {
		assert.Nil(t, resolveBufDepsWith("", t.TempDir()))
	})

	t.Run("no_cache_root_returns_nil", func(t *testing.T) {
		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		assert.Nil(t, resolveBufDepsWith(src, ""))
	})

	t.Run("missing_buf_lock_returns_nil", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		assert.Nil(t, resolveBufDepsWith(t.TempDir(), c.root))
	})

	t.Run("empty_buf_lock_returns_nil", func(t *testing.T) {
		c := newCache(t)
		src := t.TempDir()
		writeBufLock(t, src, "version: v2\n")
		assert.Nil(t, resolveBufDepsWith(src, c.root))
	})

	t.Run("malformed_buf_lock_returns_nil", func(t *testing.T) {
		c := newCache(t)
		src := t.TempDir()
		writeBufLock(t, src, "not yaml at all\n🦑\n- - - -")
		got := resolveBufDepsWith(src, c.root)
		assert.Empty(t, got)
	})

	t.Run("all_deps_missing_returns_empty", func(t *testing.T) {
		c := newCache(t)
		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		got := resolveBufDepsWith(src, c.root)
		assert.Empty(t, got)
	})

	t.Run("deduplicates_paths", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		src := t.TempDir()
		body := bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5) +
			"  - name: buf.build/bufbuild/protovalidate\n" +
			"    commit: " + fixtureCommitProtovalidate + "\n" +
			"    digest: " + fixtureDigestB5 + "\n"
		writeBufLock(t, src, body)

		got := resolveBufDepsWith(src, c.root)
		assert.Len(t, got, 1)
	})

	t.Run("b4_and_b5_both_cached_picks_per_digest", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b4", fixtureCommitProtovalidate)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		src := t.TempDir()
		writeBufLock(t, src, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB4))
		got := resolveBufDepsWith(src, c.root)
		require.Len(t, got, 1)
		assert.Contains(t, got[0], filepath.Join("v3", "modules", "b4"))

		src2 := t.TempDir()
		writeBufLock(t, src2, bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		got2 := resolveBufDepsWith(src2, c.root)
		require.Len(t, got2, 1)
		assert.Contains(t, got2[0], filepath.Join("v3", "modules", "b5"))
	})

	t.Run("v1_lock_format_works", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		src := t.TempDir()
		body := `version: v1
deps:
  - remote: buf.build
    owner: bufbuild
    repository: protovalidate
    commit: ` + fixtureCommitProtovalidate + `
    digest: ` + fixtureDigestB5 + `
`
		writeBufLock(t, src, body)
		got := resolveBufDepsWith(src, c.root)
		require.Len(t, got, 1)
	})
}

func TestResolveBufDepsFromLock(t *testing.T) {
	t.Parallel()

	t.Run("valid_lock_cached_module_returns_files_dir", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		lock := []byte(bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		got := resolveBufDepsFromLockWith(lock, c.root)
		require.Len(t, got, 1)
		assert.True(t, strings.HasSuffix(got[0], "files"))
	})

	t.Run("nil_lock_returns_nil", func(t *testing.T) {
		c := newCache(t)
		assert.Nil(t, resolveBufDepsFromLockWith(nil, c.root))
	})

	t.Run("garbage_lock_returns_nil", func(t *testing.T) {
		c := newCache(t)
		assert.Nil(t, resolveBufDepsFromLockWith([]byte("garbage"), c.root))
	})

	t.Run("empty_cache_root_returns_nil", func(t *testing.T) {
		lock := []byte(bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5))
		assert.Nil(t, resolveBufDepsFromLockWith(lock, ""))
	})

	t.Run("multiple_deps_all_cached", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)
		c.addGoogleapisMinimal("b5", fixtureCommitGoogleapis)

		lock := []byte(bufLockV2MultipleDeps())
		got := resolveBufDepsFromLockWith(lock, c.root)
		require.Len(t, got, 2)
	})

	t.Run("deduplicates_identical_paths", func(t *testing.T) {
		c := newCache(t)
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		body := bufLockV2Single(fixtureCommitProtovalidate, fixtureDigestB5) +
			"  - name: buf.build/bufbuild/protovalidate\n" +
			"    commit: " + fixtureCommitProtovalidate + "\n" +
			"    digest: " + fixtureDigestB5 + "\n"
		got := resolveBufDepsFromLockWith([]byte(body), c.root)
		assert.Len(t, got, 1)
	})

	t.Run("missing_dep_in_cache_skipped", func(t *testing.T) {
		c := newCache(t)
		// only protovalidate cached, not googleapis
		c.addProtovalidate("b5", fixtureCommitProtovalidate)

		lock := []byte(bufLockV2MultipleDeps())
		got := resolveBufDepsFromLockWith(lock, c.root)
		require.Len(t, got, 1)
		assert.Contains(t, got[0], "protovalidate")
	})
}

func TestValidModuleName(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name  string
		input string
		ok    bool
	}{
		{"standard_bsr", "buf.build/bufbuild/protovalidate", true},
		{"googleapis", "buf.build/googleapis/googleapis", true},
		{"self_hosted_hostname", "bsr.acme.internal/org/mod", true},
		{"self_hosted_with_port", "bsr.acme.internal:8443/org/mod", true},
		{"owner_with_hyphen", "buf.build/grpc-ecosystem/grpc-gateway", true},
		{"name_with_dot", "buf.build/cncf/xds", true},
		{"underscores_allowed", "buf.build/a_b/c_d", true},
		{"mixed_case_accepted", "Buf.Build/OwnerX/NameY", true},

		{"empty", "", false},
		{"two_parts", "buf.build/onlytwo", false},
		{"four_parts", "buf.build/owner/name/extra", false},
		{"trailing_slash", "buf.build/owner/", false},
		{"leading_slash", "/owner/name", false},
		{"space_in_owner", "buf.build/own er/name", false},
		{"space_in_name", "buf.build/owner/na me", false},
		{"tab_in_name", "buf.build/owner/na\tme", false},
		{"slash_in_name_part", "buf.build/owner/name/", false},
		{"emoji", "buf.build/👾/name", false},
		{"ascii_owner_name", "buf.build/owner/name", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.ok, validModuleName(tc.input), "input=%q", tc.input)
		})
	}
}

func TestSplitKV(t *testing.T) {
	t.Parallel()

	cases := []struct {
		in     string
		wantK  string
		wantV  string
		wantOk bool
	}{
		{"name: foo", "name", "foo", true},
		{"name:foo", "name", "foo", true},
		{"name:   foo   ", "name", "foo", true},
		{"name: \"quoted value\"", "name", "quoted value", true},
		{"name: 'single'", "name", "single", true},
		{"name: v # comment here", "name", "v", true},
		{"nocolon", "", "", false},
		{":leading colon", "", "", false},
		{"", "", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.in, func(t *testing.T) {
			k, v, ok := splitKV(tc.in)
			assert.Equal(t, tc.wantOk, ok)
			if ok {
				assert.Equal(t, tc.wantK, k)
				assert.Equal(t, tc.wantV, v)
			}
		})
	}
}
